apiVersion: apps/v1
kind: Deployment
metadata:
  name: tspencerenv
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tspencerenv
  template:
    metadata:
      labels:
        app: tspencerenv
    spec:
      containers:
      - name: terraform
        image: gsatspencer/identity-terraform:1.0.30
        resources:
          requests:
            memory: "1024Mi"
            cpu: ".1"
          limits:
            memory: "2048Mi"
            cpu: "1"
        env:
        - name: TF_ENVIRONMENT
          value: "tspencer"
        - name: TF_DIR
          value: "app"
        - name: TF_IDPHOSTNAME
          value: "idp.tspencer.identitysandbox.gov"
        - name: BRANCH
          value: "stages/tspencer"
        volumeMounts:
        - name: deploy-key
          mountPath: "/root/.ssh"
          readOnly: true
      volumes:
      - name: deploy-key
        secret:
          secretName: deploy-key
          defaultMode: 0400
