apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: eks
spec:
  # profile: eks
  # components:
  #   telemetry:
  #     enabled: false
  #   egressGateways:
  #     enabled: true
  #   ingressGateways:
  #     enabled: true

  # addonComponents:
  #   kiali:
  #     enabled: true
  #   prometheus:
  #     enabled: true
  #   grafana:
  #     enabled: true
  #   tracing:
  #     enabled: true

  # meshconfig:
  #   accessLogFile: /dev/stdout
  #   accessLogFormat: JSON

  # values:
  #   kiali:
  #     createDemoSecret: true
