apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: eks
  labels:
    app.kubernetes.io/instance: istio
spec:
  profile: default
  components:
    telemetry:
      enabled: false
    egressGateways:
      enabled: true
    ingressGateways:
      enabled: true

  addonComponents:
    kiali:
      enabled: true
      spec:
        createDemoSecret: true
    prometheus:
      enabled: true
    grafana:
      enabled: true
    tracing:
      enabled: true

  values:
    meshconfig:
      accessLogFile: /dev/stdout
      accessLogFormat: JSON
