apiVersion: v1
kind: Service
metadata:
  labels:
    app: logstash
  name: logstash
spec:
  ports:
  - name: http-25826
    port: 25826
    targetPort: 25826
  - name: http-beats
    port: 5044
    targetPort: 5044
  selector:
    app: logstash

