apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: terraform
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # Project description
  description: Terraform Stuff

  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - 'https://github.com/18F/identity-eks.git'

  # Only permit applications to deploy to the proper namespaces in the same cluster
  destinations:
  - namespace: terraform
    server: https://kubernetes.default.svc

  # Allow all namespaced-scoped resources to be created, except for ResourceQuota, LimitRange, NetworkPolicy
  namespaceResourceBlacklist:
  - group: ''
    kind: ResourceQuota
  - group: ''
    kind: LimitRange
  - group: ''
    kind: NetworkPolicy

  # Deny all namespaced-scoped resources from being created, except for Deployment and StatefulSet
  namespaceResourceWhitelist:
    kind: Job

  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: false

