filebeatConfig:
  filebeat.yml: |
    logging.level: debug
    filebeat.inputs:
    - type: docker
      containers.ids:
      - '*'
      processors:
      - add_kubernetes_metadata: ~
      - decode_json_fields:
          fields: ["message"]
          process_array: false
          max_depth: 2
          target: "json"
          overwrite_keys: false
          add_error_key: true
      #json:
      #- keys_under_root: true

    setup.ilm.policy_name: 'expire90days'

