---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: consul-only
  namespace: elk
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8600
    - protocol: UDP
      port: 8600
    - protocol: TCP
      port: 8500
    - protocol: TCP
      port: 8501
    - protocol: TCP
      port: 8502
    - protocol: TCP
      port: 8301
    - protocol: UDP
      port: 8301
    - protocol: TCP
      port: 8302
    - protocol: UDP
      port: 8302
    - protocol: TCP
      port: 8300
    - protocol: TCP
      port: 21000-21255
  egress:
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 8600
    - protocol: UDP
      port: 8600
    - protocol: TCP
      port: 8500
    - protocol: TCP
      port: 8501
    - protocol: TCP
      port: 8502
    - protocol: TCP
      port: 8301
    - protocol: UDP
      port: 8301
    - protocol: TCP
      port: 8302
    - protocol: UDP
      port: 8302
    - protocol: TCP
      port: 8300
    - protocol: TCP
      port: 21000-21255

