apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  # You'll usually want to add your resources to the argocd namespace.
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: https://charts.jetstack.io
    # You should probably also go get the latest crds.  For this version, you can get them with
    # wget https://github.com/jetstack/cert-manager/releases/download/v0.16.1/cert-manager.crds.yaml
    targetRevision: 0.16.1
    chart: cert-manager
    helm:
      values: |
        podAnnotations:
          linkerd.io/inject: enabled
        webhook:
          podAnnotations:
            linkerd.io/inject: enabled
        cainjector:
          podAnnotations:
            linkerd.io/inject: enabled


  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  # Sync policy
  syncPolicy:
    automated:
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:     # Sync options which modifies sync behavior
    - Validate=false # disables resource validation (equivalent to 'kubectl apply --validate=true')

  # Ignore differences at the specified json pointers
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status

