resources:
  - cert-manager-ns.yaml
  - cert-manager.crds.yaml
  - cert-manager.yaml
  - falco.yaml
  - clamav.yaml
  - elk.yaml
  - filebeat.yaml
  - dashboard.yaml
  - metrics-server.yaml
  - flagger.yaml

